services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ~/ollama:/root/.ollama
    
    healthcheck:
      test: "ollama list || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
